# Path to your oh-my-zsh configuration.
ZSH_CUSTOM=$HOME/dotfiles/oh-my-zsh-custom
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(git macos)

source $ZSH/oh-my-zsh.sh

#aliases

# cd
alias ..="cd .."
alias cd..="cd .."

#ls
alias ls="ls -FGh"
alias a="ls -a"
alias ll="ls -lh"
alias la='ls -lah'

alias dot="cd ~/dotfiles"
alias reload="omz reload"
alias lazy="lazygit"

eval $(thefuck --alias fuck)

eval "$(starship init zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

export NVM_DIR="$HOME/.nvm"
    [ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" # This loads nvm
    [ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
