# Path to your oh-my-zsh configuration.
ZSH_CUSTOM=$HOME/dotfiles/oh-my-zsh-custom
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(git macos)

source $ZSH/oh-my-zsh.sh


eval $(thefuck --alias fuck)

eval "$(starship init zsh)"
